"""inference models path

Revision ID: 0b3e3440eff8
Revises: 914786c02f2f
Create Date: 2026-05-18 18:41:58.175090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3e3440eff8'
down_revision: Union[str, Sequence[str], None] = '914786c02f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_models', sa.Column('path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_models', 'path')
    # ### end Alembic commands ###
