"""inference models addition 1M

Revision ID: 914786c02f2f
Revises: d90b1691d66c
Create Date: 2026-05-18 18:40:50.918795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914786c02f2f'
down_revision: Union[str, Sequence[str], None] = 'd90b1691d66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('inference_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'inference_models', ['inference_model_id'], ['id'])
    op.drop_constraint(op.f('inference_models_dataset_id_key'), 'inference_models', type_='unique')
    op.drop_constraint(op.f('inference_models_dataset_id_fkey'), 'inference_models', type_='foreignkey')
    op.drop_column('inference_models', 'dataset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_models', sa.Column('dataset_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('inference_models_dataset_id_fkey'), 'inference_models', 'datasets', ['dataset_id'], ['id'])
    op.create_unique_constraint(op.f('inference_models_dataset_id_key'), 'inference_models', ['dataset_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'inference_model_id')
    # ### end Alembic commands ###
