"""added back inference actions

Revision ID: 9a30c214507f
Revises: c197d056a8f8
Create Date: 2026-05-09 17:42:56.593338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models

# revision identifiers, used by Alembic.
revision: str = '9a30c214507f'
down_revision: Union[str, Sequence[str], None] = 'c197d056a8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', models.inference_action.ActionIntType(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.CheckConstraint('action_id <> 0', name='inference_actions_action_id_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_index(op.f('ix_inference_actions_id'), 'inference_actions', ['id'], unique=False)
    op.alter_column('inference_history_classification', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('inference_history_classification', 'ground_truth',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inference_history_classification', 'prediction',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inference_history_classification', 'inference_history_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inference_history_people_tracking', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('inference_history_people_tracking', 'people_tracked',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference_history_people_tracking', 'people_tracked',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inference_history_people_tracking', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('inference_history_classification', 'inference_history_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inference_history_classification', 'prediction',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('inference_history_classification', 'ground_truth',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('inference_history_classification', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_index(op.f('ix_inference_actions_id'), table_name='inference_actions')
    op.drop_table('inference_actions')
    # ### end Alembic commands ###
