"""bd_refactoring

Revision ID: c197d056a8f8
Revises: 
Create Date: 2026-05-07 16:48:37.491272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c197d056a8f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_actions')
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_inference_history_classification_id'), 'inference_history_classification', ['id'], unique=False)
    op.create_index(op.f('ix_inference_history_classification_inference_history_id'), 'inference_history_classification', ['inference_history_id'], unique=False)
    op.create_index(op.f('ix_inference_history_people_tracking_id'), 'inference_history_people_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_inference_history_people_tracking_inference_history_id'), 'inference_history_people_tracking', ['inference_history_id'], unique=False)
    op.alter_column('users', 'ban_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('videos', 'uid',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('videos', 'dataset_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_videos_name'), table_name='videos')
    op.drop_index(op.f('ix_videos_path'), table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_path'), 'videos', ['path'], unique=True)
    op.create_index(op.f('ix_videos_name'), 'videos', ['name'], unique=False)
    op.alter_column('videos', 'dataset_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('videos', 'uid',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'ban_reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inference_history_people_tracking_inference_history_id'), table_name='inference_history_people_tracking')
    op.drop_index(op.f('ix_inference_history_people_tracking_id'), table_name='inference_history_people_tracking')
    op.drop_index(op.f('ix_inference_history_classification_inference_history_id'), table_name='inference_history_classification')
    op.drop_index(op.f('ix_inference_history_classification_id'), table_name='inference_history_classification')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.create_table('inference_actions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_id <> 0', name=op.f('chk_valid_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('inference_actions_pkey')),
    sa.UniqueConstraint('action_id', name=op.f('inference_actions_action_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
