"""inference models addition

Revision ID: d90b1691d66c
Revises: 9a30c214507f
Create Date: 2026-05-18 18:28:55.795778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90b1691d66c'
down_revision: Union[str, Sequence[str], None] = '9a30c214507f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_inference_models_id'), 'inference_models', ['id'], unique=False)
    op.drop_column('datasets', 'inference_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('inference_model_id', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inference_models_id'), table_name='inference_models')
    op.drop_table('inference_models')
    # ### end Alembic commands ###
