services:
  violens-service:
    build:
      context: .
      dockerfile: ./violens_service/Dockerfile
    container_name: violens_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./violens_service/.env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/code/app
    networks:
      - violens_net
    working_dir: /code/app

  classification-service:
    build:
      context: .
      dockerfile: ./classification_service/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    container_name: classification_service
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - ./classification_service/.env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/code/app
    networks:
      - violens_net
    working_dir: /code/app

  people-tracking-service:
    build:
      context: .
      dockerfile: ./people_tracking_service/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    container_name: people_tracking_service
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - ./people_tracking_service/.env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/code/app
    networks:
      - violens_net
    working_dir: /code/app

networks:
  violens_net: