/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenSchema } from '../../models/token-schema';
import { UserResponseDto } from '../../models/user-response-dto';

export interface LoginGoogleAuthGoogleLoginPost$Params {
      body: TokenSchema
}

export function loginGoogleAuthGoogleLoginPost(http: HttpClient, rootUrl: string, params: LoginGoogleAuthGoogleLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, loginGoogleAuthGoogleLoginPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

loginGoogleAuthGoogleLoginPost.PATH = '/auth/google-login';
