/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Action } from './action';

/**
 * Each possible value of `Action`
 */
export const ACTION: Action[] = [
  0,
  10,
  20
];