/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfusionMatrixDto {
  false_negative: number;
  false_positive: number;
  true_negative: number;
  true_positive: number;
}
