/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {
  ban_reason?: (string | null);
  credits?: number;
  email: string;
  is_active?: boolean;
  is_admin?: boolean;
  is_banned?: boolean;
  password: string;
}
