/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {
  auth_provider?: (string | null);
  credits?: number;
  email: string;
  is_active?: boolean;
  is_admin?: boolean;
  password: string;
}
