/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InferenceHistoryClassificationStatsResponseDto {
  created_at: string;
  ground_truth: boolean;
  id: number;
  prediction: boolean;
}
