/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InferenceHistoryClassificationStatsResponseDto } from '../models/inference-history-classification-stats-response-dto';
import { InferenceHistoryPeopleTrackingStatsResponseDto } from '../models/inference-history-people-tracking-stats-response-dto';
export interface InferenceHistoryStatsResponseDto {
  classification_runs: Array<InferenceHistoryClassificationStatsResponseDto>;
  people_tracking_runs: Array<InferenceHistoryPeopleTrackingStatsResponseDto>;
}
