/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InferenceHistoryPeopleTrackingStatsResponseDto {
  created_at: string;
  id: number;
  people_tracked: number;
}
