/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Action } from '../models/action';
export interface InferenceActionResponseDto {
  action_id: Action;
  credits: number;
  id: number;
  name: string;
}
