/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateInferenceActionRequestDto } from '../models/update-inference-action-request-dto';
export interface PatchInferenceActionRequestDto {
  actions: Array<UpdateInferenceActionRequestDto>;
}
