/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponseDto {
  credits?: number;
  email: string;
  id: number;
  is_active?: boolean;
  is_admin?: boolean;
}
