/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponseDto {
  ban_reason?: (string | null);
  credits?: number;
  credits_used?: (number | null);
  email: string;
  id: number;
  is_active?: boolean;
  is_admin?: boolean;
  is_banned?: boolean;
}
