/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewVideoRequestDto } from '../models/review-video-request-dto';
export interface ValidateModelRequestDto {
  excluded_video_ids?: (Array<number> | null);
  videos: Array<ReviewVideoRequestDto>;
}
