/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConfusionMatrixDto } from '../models/confusion-matrix-dto';
export interface ValidateModelResponseDto {
  accuracy: number;
  confusion_matrix: ConfusionMatrixDto;
}
