/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VideoResponseDto {
  dataset_id: number;
  dataset_is_official: boolean;
  dataset_name: string;
  duration: number;
  frame_rate: number;
  id: number;
  is_violent: (boolean | null);
  name: string;
  path: string;
  uid: string;
}
