/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VideoResponseDto {
  dataset_id: number;
  dataset_name: string;
  duration: number;
  id: number;
  is_violent: boolean;
  name: string;
  path: string;
}
