/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsersStatsResponseDto } from '../../models/users-stats-response-dto';

export interface GetUsersStatsUsersGetUsersStatsGet$Params {
}

export function getUsersStatsUsersGetUsersStatsGet(http: HttpClient, rootUrl: string, params?: GetUsersStatsUsersGetUsersStatsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UsersStatsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getUsersStatsUsersGetUsersStatsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsersStatsResponseDto>;
    })
  );
}

getUsersStatsUsersGetUsersStatsGet.PATH = '/users/get_users_stats';
