/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RequestResetPasswordUsersRequestResetPasswordGet$Params {
  email: string;
}

export function requestResetPasswordUsersRequestResetPasswordGet(http: HttpClient, rootUrl: string, params: RequestResetPasswordUsersRequestResetPasswordGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, requestResetPasswordUsersRequestResetPasswordGet.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

requestResetPasswordUsersRequestResetPasswordGet.PATH = '/users/request_reset_password';
