/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponseDto } from '../../models/user-response-dto';

export interface ResendVerificationEmailUsersResendVerificationEmailGet$Params {
  token: string;
}

export function resendVerificationEmailUsersResendVerificationEmailGet(http: HttpClient, rootUrl: string, params: ResendVerificationEmailUsersResendVerificationEmailGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, resendVerificationEmailUsersResendVerificationEmailGet.PATH, 'get');
  if (params) {
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

resendVerificationEmailUsersResendVerificationEmailGet.PATH = '/users/resend_verification_email';
