/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateUserRoleUsersUpdateUserRolePatch$Params {
  user_id: number;
  is_admin: boolean;
}

export function updateUserRoleUsersUpdateUserRolePatch(http: HttpClient, rootUrl: string, params: UpdateUserRoleUsersUpdateUserRolePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateUserRoleUsersUpdateUserRolePatch.PATH, 'patch');
  if (params) {
    rb.query('user_id', params.user_id, {});
    rb.query('is_admin', params.is_admin, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateUserRoleUsersUpdateUserRolePatch.PATH = '/users/update_user_role';
