/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface VerifyResetPasswordTokenUsersVerifyResetPasswordTokenGet$Params {
  token: string;
}

export function verifyResetPasswordTokenUsersVerifyResetPasswordTokenGet(http: HttpClient, rootUrl: string, params: VerifyResetPasswordTokenUsersVerifyResetPasswordTokenGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, verifyResetPasswordTokenUsersVerifyResetPasswordTokenGet.PATH, 'get');
  if (params) {
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

verifyResetPasswordTokenUsersVerifyResetPasswordTokenGet.PATH = '/users/verify_reset_password_token';
