"""Added boolean column for account verification

Revision ID: 589e0974fbb8
Revises: 0270e5869b2b
Create Date: 2026-03-16 19:49:20.151004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589e0974fbb8'
down_revision: Union[str, Sequence[str], None] = '0270e5869b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_account_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_account_verified')
    # ### end Alembic commands ###
