"""removed unique constraint for video names

Revision ID: ae5d646ab137
Revises: 5313854e8828
Create Date: 2026-03-09 17:17:18.520926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5d646ab137'
down_revision: Union[str, Sequence[str], None] = '5313854e8828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_name'), table_name='videos')
    op.create_index(op.f('ix_videos_name'), 'videos', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_name'), table_name='videos')
    op.create_index(op.f('ix_videos_name'), 'videos', ['name'], unique=True)
    # ### end Alembic commands ###
