"""added path column for videos table

Revision ID: cc8a3c21500e
Revises: 172bb1fe9800
Create Date: 2026-03-09 16:53:18.461471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8a3c21500e'
down_revision: Union[str, Sequence[str], None] = '172bb1fe9800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('path', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_videos_path'), 'videos', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_path'), table_name='videos')
    op.drop_column('videos', 'path')
    # ### end Alembic commands ###
