/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InferenceHistoryStatsResponseDto } from '../../models/inference-history-stats-response-dto';

export interface GetInferenceHistoryStatsInferenceHistoryGetInferenceHistoryStatsGet$Params {
  year?: (number | null);
  month?: (number | null);
}

export function getInferenceHistoryStatsInferenceHistoryGetInferenceHistoryStatsGet(http: HttpClient, rootUrl: string, params?: GetInferenceHistoryStatsInferenceHistoryGetInferenceHistoryStatsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<InferenceHistoryStatsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getInferenceHistoryStatsInferenceHistoryGetInferenceHistoryStatsGet.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InferenceHistoryStatsResponseDto>;
    })
  );
}

getInferenceHistoryStatsInferenceHistoryGetInferenceHistoryStatsGet.PATH = '/inference_history/get_inference_history_stats';
