/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InferenceActionResponseDto } from '../../models/inference-action-response-dto';

export interface GetInferenceActionsInferenceActionsGetInferenceActionsGet$Params {
}

export function getInferenceActionsInferenceActionsGetInferenceActionsGet(http: HttpClient, rootUrl: string, params?: GetInferenceActionsInferenceActionsGetInferenceActionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InferenceActionResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getInferenceActionsInferenceActionsGetInferenceActionsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InferenceActionResponseDto>>;
    })
  );
}

getInferenceActionsInferenceActionsGetInferenceActionsGet.PATH = '/inference_actions/get_inference_actions';
