/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatchInferenceActionRequestDto } from '../../models/patch-inference-action-request-dto';

export interface UpdateCreditsForActionInferenceActionsUpdateCreditsInferenceActionsPatch$Params {
      body: PatchInferenceActionRequestDto
}

export function updateCreditsForActionInferenceActionsUpdateCreditsInferenceActionsPatch(http: HttpClient, rootUrl: string, params: UpdateCreditsForActionInferenceActionsUpdateCreditsInferenceActionsPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateCreditsForActionInferenceActionsUpdateCreditsInferenceActionsPatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateCreditsForActionInferenceActionsUpdateCreditsInferenceActionsPatch.PATH = '/inference_actions/update_credits_inference_actions';
