/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Action } from '../../models/action';
import { InferenceActionResponseDto } from '../../models/inference-action-response-dto';

export interface UpdateCreditsForActionInferenceActionsUpdateCreditsForActionPatch$Params {
  action_id: Action;
  credits: number;
}

export function updateCreditsForActionInferenceActionsUpdateCreditsForActionPatch(http: HttpClient, rootUrl: string, params: UpdateCreditsForActionInferenceActionsUpdateCreditsForActionPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<InferenceActionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateCreditsForActionInferenceActionsUpdateCreditsForActionPatch.PATH, 'patch');
  if (params) {
    rb.query('action_id', params.action_id, {});
    rb.query('credits', params.credits, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InferenceActionResponseDto>;
    })
  );
}

updateCreditsForActionInferenceActionsUpdateCreditsForActionPatch.PATH = '/inference_actions/update_credits_for_action';
