/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Dataset } from '../../models/dataset';
import { VideoResponseDto } from '../../models/video-response-dto';

export interface GetVideosPagedVideosGetVideosPagedGet$Params {
  asc?: boolean;
  page?: number;
  page_size?: number;
  is_violent?: (boolean | null);
  search_term?: (string | null);
  dataset_id?: (Dataset | null);
}

export function getVideosPagedVideosGetVideosPagedGet(http: HttpClient, rootUrl: string, params?: GetVideosPagedVideosGetVideosPagedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VideoResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getVideosPagedVideosGetVideosPagedGet.PATH, 'get');
  if (params) {
    rb.query('asc', params.asc, {});
    rb.query('page', params.page, {});
    rb.query('page_size', params.page_size, {});
    rb.query('is_violent', params.is_violent, {});
    rb.query('search_term', params.search_term, {});
    rb.query('dataset_id', params.dataset_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VideoResponseDto>>;
    })
  );
}

getVideosPagedVideosGetVideosPagedGet.PATH = '/videos/get_videos_paged';
