/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PeopleTrackingVideosPeopleTrackingVideoIdPost$Params {
  video_id: number;
}

export function peopleTrackingVideosPeopleTrackingVideoIdPost(http: HttpClient, rootUrl: string, params: PeopleTrackingVideosPeopleTrackingVideoIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, peopleTrackingVideosPeopleTrackingVideoIdPost.PATH, 'post');
  if (params) {
    rb.path('video_id', params.video_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

peopleTrackingVideosPeopleTrackingVideoIdPost.PATH = '/videos/people_tracking/{video_id}';
