from api.dependencies.auth_service import get_auth_service
from api.dependencies.credits_service import get_credits_service
from api.dependencies.datasets_service import get_datasets_service
from api.dependencies.inference_actions_service import get_inference_actions_service
from api.dependencies.inference_history_service import get_inference_history_service
from api.dependencies.users_service import get_users_service
from api.dependencies.videos_service import get_videos_service

