/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PatchCreditsCronjobUpdateCreditsPatchCreditsCronjobUpdatePatch$Params {
  new_credits: number;
}

export function patchCreditsCronjobUpdateCreditsPatchCreditsCronjobUpdatePatch(http: HttpClient, rootUrl: string, params: PatchCreditsCronjobUpdateCreditsPatchCreditsCronjobUpdatePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, patchCreditsCronjobUpdateCreditsPatchCreditsCronjobUpdatePatch.PATH, 'patch');
  if (params) {
    rb.query('new_credits', params.new_credits, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

patchCreditsCronjobUpdateCreditsPatchCreditsCronjobUpdatePatch.PATH = '/credits/patch_credits_cronjob_update';
